"""Fulcrum-Anbindung über das Electrum-Protokoll (TCP/SSL).

Dünne Re-Export-Fassade nach Slice-5-Schritten 1–5. Fachcode liegt unter
``core/fulcrum_transport``, ``core/fulcrum_client``, ``core/fulcrum_wallet``,
``core/fulcrum_history``. Symbol-Identität: ``fulcrum.X is core.fulcrum_*.X``.
"""
from __future__ import annotations

from core.fulcrum_transport import (
    TOR_BROWSER_DOWNLOAD,
    TOR_BROWSER_SOCKS_HOST,
    TOR_BROWSER_SOCKS_PORT,
    TOR_EXPERT_SOCKS_PORT,
    TOR_PROXY_CHECK_TIMEOUT,
    _recv_exact,
    _socks5_connect,
    resolve_tor_proxy,
    socks_proxy_reachable,
)

from core.fulcrum_client import (
    CLIENT_NAME,
    FULCRUM_CONNECT_TIMEOUT,
    FULCRUM_DEFAULT_PORT,
    FULCRUM_ONION_TIMEOUT,
    FULCRUM_REQUEST_RETRIES,
    PROTOCOL_VERSION,
    TOR_RPC_BATCH_SIZE,
    FulcrumClient,
    FulcrumNotifySession,
    RotatingFulcrumPool,
    SanctionsClearnetPool,
    _GET_HISTORY_METHOD,
    _LISTUNSPENT_METHOD,
    _PROBE_SCRIPT_HASH,
    _is_unknown_method_error,
    address_to_scripthash,
    connect_fulcrum,
    parallel_ueber_pool,
    parse_electrum_server_software,
    supports_listunspent,
)

from core.fulcrum_wallet import (
    _adressen_fuer_index,
    _collect_used_chain_indices_tor_batch,
    _fetch_wallet_utxos_tor_batch,
    _gap_progress,
    _spender_map_fuer_outpoints,
    _utxos_from_listunspent_entries,
    address_has_received_fulcrum,
    collect_used_chain_indices_fulcrum,
    collect_used_receive_indices_fulcrum,
    eigene_mempool_empfaenge,
    fetch_address_utxos_fulcrum,
    fetch_wallet_utxos_fulcrum,
    finde_mempool_spends_utxos,
    first_seen_fulcrum,
    first_seen_height_fulcrum,
    klassifiziere_utxo_spends,
    mempool_tx_hat_eigenen_output,
)

from core.fulcrum_history import (
    SANCTIONS_HISTORY_PROBE_HEIGHT,
    _DATE_HEIGHT_CACHE,
    _HEADER_TIME_CACHE,
    _TIP_HEIGHT_CACHE,
    _TIP_SEARCH_CEILING,
    _TX_HEIGHT_CACHE,
    _VERBOSE_TX_UNSUPPORTED,
    _block_time_for_height,
    _enrich_tx_block_info,
    _fetch_address_utxos_from_history,
    _fetch_block_header_hex,
    _fulcrum_client_cache_key,
    _header_exists_at_height,
    _lookup_tx_height,
    _normalize_electrum_tx,
    _parse_tx_hex,
    _parse_utc_date_timestamp,
    _script_pubkey_to_dict,
    _status_fuer_hoehe,
    _timestamp_from_block_header,
    _tip_height_via_binary_search,
    _tx_block_time_from_dict,
    _verbose_tx_unsupported,
    _vin_to_dict,
    _vout_addresses,
    _vout_matches_address,
    _vout_value_sats,
    _verlauf_fortschritt,
    _walk_address_history,
    date_to_block_height_fulcrum,
    fetch_address_history_fulcrum,
    fetch_tx_fulcrum,
    fetch_txs_fulcrum_batch,
    fetch_wallet_history_fulcrum,
    get_chain_tip_height,
    supports_historical_headers,
)

