# SatSage StartOS package. Package root is this directory (`packaging/`).
# Build: from a Start9 workspace, `cd packaging && make x86`
# Docs:  ../doc/START9-packaging.md
ARCHES := x86
include node_modules/@start9labs/start-sdk/s9pk.mk
